/**
 * pregnancyContent.en.ts — English mirror of pregnancyContent.ts.
 * Same shapes, idiomatic English. Used when i18n.language is "en".
 * Keep in sync with the Danish source when content is edited.
 */

import type { WeekContent, TrimesterContent } from "./pregnancyContent";

// ──────────────────────────────────────────────────────────────────────────────
// PER-WEEK CONTENT (weeks 5–40)
// ──────────────────────────────────────────────────────────────────────────────

export const pregnancyWeeksEN: Record<number, WeekContent> = {
  5: {
    week: 5, trimester: 1,
    babyDev: "The embryo is the size of a sesame seed. The neural tube is forming — it becomes brain and spinal cord.",
    motherBody: "You're producing large amounts of HCG now. Nausea, fatigue and tender breasts can be the first signs.",
    highlight: "The heart begins to form",
    highlightEmoji: "💗",
    facts: ["Neural tube forms — becomes brain and spinal cord", "The heart begins to take shape", "The embryo is the size of a sesame seed"],
    nutrition: [
      { icon: "🥦", text: "Folic acid (400 µg/day) is critical — protects the neural tube" },
      { icon: "🚫", text: "Avoid all alcohol — no amount is safe" },
      { icon: "💊", text: "Start vitamin D (10 µg/day) immediately" },
    ],
    partnerFocus: "She's more tired than ever — not by choice. Her body is working hard. Take over dinner.",
    activeVitamins: ["folsyre", "d-vitamin"],
  },
  6: {
    week: 6, trimester: 1,
    babyDev: "The heart beats for the first time — about 100 beats per minute. Eyes, ears and nose are starting to form.",
    motherBody: "Nausea typically peaks morning and evening. Keep crackers by the bed. Small, frequent meals help.",
    highlight: "The heart beats for the first time",
    highlightEmoji: "💓",
    facts: ["The heart beats — about 100 bpm", "Eyes, ears and nose begin to form", "Embryo size of a lentil"],
    nutrition: [
      { icon: "🥦", text: "Folic acid: leafy greens, lentils and nuts daily" },
      { icon: "🍋", text: "Sour foods and cold drinks can ease morning sickness" },
      { icon: "🫚", text: "Eat little and often — keeps blood sugar steady" },
    ],
    partnerFocus: "Her sense of smell is dramatically heightened. Keep strong scents (soap, candles, food) at bay.",
    activeVitamins: ["folsyre", "d-vitamin"],
  },
  7: {
    week: 7, trimester: 1,
    babyDev: "The embryo is the size of a blueberry. The brain is growing fast — many new neural connections daily.",
    motherBody: "The uterus is about twice its normal size now. You may feel pressure in the pelvis.",
    highlight: "The brain is growing fast",
    highlightEmoji: "🧠",
    facts: ["Brain develops fast", "Facial features start to hint", "Embryo size of a blueberry"],
    nutrition: [
      { icon: "🥦", text: "Folic acid still daily" },
      { icon: "💧", text: "1.5–2 L of water daily — also helps with nausea" },
      { icon: "🥜", text: "Small portions of protein stabilize energy" },
    ],
    partnerFocus: "Book the first midwife appointment this week if you haven't.",
    activeVitamins: ["folsyre", "d-vitamin"],
  },
  8: {
    week: 8, trimester: 1,
    babyDev: "All vital organs are laid down. Baby has fingers — with webbing that slowly disappears.",
    motherBody: "Many experience peak nausea weeks 8–10. It's a sign HCG is high — actually a good sign.",
    highlight: "All organs laid down",
    highlightEmoji: "✅",
    facts: ["Vital organs in place", "Fingers and toes form", "About 1.6 cm"],
    nutrition: [
      { icon: "🥦", text: "Folic acid critical through week 12" },
      { icon: "🥛", text: "Calcium from dairy — baby's bones are forming" },
      { icon: "🚫", text: "Avoid liver and liver pâté — too much vitamin A" },
    ],
    partnerFocus: "First scan is approaching — be there. It's your first shared experience of the baby.",
    activeVitamins: ["folsyre", "d-vitamin"],
  },
  9: {
    week: 9, trimester: 1,
    babyDev: "Now called a fetus. The tail is gone. Baby can swallow and kick — you just can't feel it yet.",
    motherBody: "The pelvic floor is carrying extra weight. Start gentle pelvic floor exercises now.",
    highlight: "Fetal stage begins",
    highlightEmoji: "🌱",
    facts: ["Embryo becomes fetus", "Baby can swallow and kick", "Tail is gone"],
    nutrition: [
      { icon: "🐟", text: "Omega-3 from oily fish supports brain development" },
      { icon: "🥛", text: "Calcium + vitamin D for early bone formation" },
      { icon: "🫐", text: "Berries against cellular stress" },
    ],
    partnerFocus: "Ask about nausea and energy — listen instead of fixing.",
    activeVitamins: ["folsyre", "d-vitamin"],
  },
  10: {
    week: 10, trimester: 1,
    babyDev: "Baby is the size of an olive and can bend its arms. Fingernails start to form.",
    motherBody: "Blood volume rises. You may feel dizziness and palpitations — that's normal.",
    highlight: "Baby can bend its arms",
    highlightEmoji: "💪",
    facts: ["Baby can bend and stretch arms", "Fingernails begin", "Blood volume rising"],
    nutrition: [
      { icon: "🥩", text: "Iron matters now — blood volume rises" },
      { icon: "🍊", text: "Vitamin C boosts iron absorption from plant sources" },
      { icon: "🌾", text: "Whole grains give steady energy and prevent constipation" },
    ],
    partnerFocus: "Look into parental leave and benefits — it takes time.",
    activeVitamins: ["folsyre", "d-vitamin", "jern"],
  },
  11: {
    week: 11, trimester: 1,
    babyDev: "Baby's bones begin to harden. Fingers are no longer fused. Genitals are forming.",
    motherBody: "Nausea is easing for many. Energy slowly returns.",
    highlight: "Bones begin to harden",
    highlightEmoji: "🦴",
    facts: ["Bones hardening", "Fingers and toes separated", "Kidneys produce urine"],
    nutrition: [
      { icon: "🌾", text: "Fibre from oats and vegetables prevents constipation" },
      { icon: "🥦", text: "Leafy greens: folate, iron and calcium in one" },
      { icon: "💧", text: "1.5–2 L water daily — frequent peeing is normal" },
    ],
    partnerFocus: "Book the nuchal scan (weeks 11–14) if you want it.",
    activeVitamins: ["folsyre", "d-vitamin", "jern"],
  },
  12: {
    week: 12, trimester: 1,
    babyDev: "Baby is about 5 cm long. Can open the mouth and stretch fingers. Kidneys are working.",
    motherBody: "1st trimester ends! Risk of miscarriage drops sharply. Many share the news now.",
    highlight: "1st trimester complete",
    highlightEmoji: "🎉",
    facts: ["1st trimester complete", "Baby about 5 cm", "Can open mouth"],
    nutrition: [
      { icon: "🥩", text: "Iron grows in importance — blood mass rising" },
      { icon: "🥛", text: "Calcium ~1000 mg/day — baby's skeleton hardening" },
      { icon: "🚫", text: "Avoid raw fish, unpasteurized cheese, raw eggs" },
    ],
    partnerFocus: "Nuchal scan this week — take time off and be there.",
    activeVitamins: ["folsyre", "d-vitamin", "jern", "calcium"],
  },
  13: {
    week: 13, trimester: 2,
    babyDev: "Baby has fingerprints. The face is fully formed. Baby can suck its thumb.",
    motherBody: "The bump starts to show. Many feel increased energy in the 2nd trimester.",
    highlight: "Fingerprints form",
    highlightEmoji: "👆",
    facts: ["Unique fingerprints", "Baby sucks thumb", "Energy returns for many"],
    nutrition: [
      { icon: "🥩", text: "Iron and protein daily" },
      { icon: "🐟", text: "Oily fish 1–2 times a week — salmon, herring, mackerel" },
      { icon: "🥦", text: "Folate from greens and legumes" },
    ],
    partnerFocus: "Talk about your expectations of each other as parents — easier now than after birth.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  14: {
    week: 14, trimester: 2,
    babyDev: "Baby practices breathing movements and the swallow reflex with amniotic fluid.",
    motherBody: "The uterus is now above the pubic bone. You may feel slight pressure from above.",
    highlight: "Baby practices breathing",
    highlightEmoji: "🫁",
    facts: ["Baby practices breathing", "Swallow reflex trained", "Uterus rises above pubic bone"],
    nutrition: [
      { icon: "🫐", text: "Berries + vitamin C boost iron absorption" },
      { icon: "🥜", text: "Nuts and seeds: healthy fat, magnesium, vitamin E" },
      { icon: "💧", text: "Drink plenty — amniotic fluid production rises" },
    ],
    partnerFocus: "Look at birth options together. Hospital, birth center or home? Start the conversation.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  15: {
    week: 15, trimester: 2,
    babyDev: "Baby can hear sounds from outside. Talk to your bump — baby already knows your voice.",
    motherBody: "Many feel round ligament pain — sharp pains in the side. That's normal.",
    highlight: "Baby can hear your voice",
    highlightEmoji: "👂",
    facts: ["Baby hears outside sounds", "Ligament pains are normal", "Hearing sharpens"],
    nutrition: [
      { icon: "🐟", text: "Oily fish 2× a week — omega-3 for hearing and vision" },
      { icon: "🥦", text: "Leafy greens: iron and folate still important" },
      { icon: "🫘", text: "Beans and lentils: plant iron and protein" },
    ],
    partnerFocus: "Start talking to the bump — baby will know your voice at birth.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  16: {
    week: 16, trimester: 2,
    babyDev: "Baby is the size of an avocado. Muscles and bones grow fast. The eyes move.",
    motherBody: "Some feel the first gentle kicks — like butterflies or bubbles.",
    highlight: "First kicks possible",
    highlightEmoji: "🦋",
    facts: ["First kicks felt", "Muscles and bones grow", "Eyes are moving"],
    nutrition: [
      { icon: "🥩", text: "Iron for baby's red blood cells" },
      { icon: "🥛", text: "Calcium extra important — bone hardening in full swing" },
      { icon: "🌾", text: "Complex carbs give steady energy" },
    ],
    partnerFocus: "Place a hand on the bump daily. That's your way of making contact.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  17: {
    week: 17, trimester: 2,
    babyDev: "Baby is covered in lanugo — fine down that keeps warmth. A fat layer starts to form.",
    motherBody: "Back pain is common now. A pregnancy pillow at night helps. Avoid standing for long.",
    highlight: "Lanugo covers the body",
    highlightEmoji: "🌫️",
    facts: ["Lanugo covers skin", "Fat layer begins", "Back pain common"],
    nutrition: [
      { icon: "🐟", text: "Omega-3 + vitamin E support fat tissue formation" },
      { icon: "🥜", text: "Almonds and sunflower seeds: cell-protective vitamin E" },
      { icon: "💧", text: "Plenty of water helps swollen ankles and heartburn" },
    ],
    partnerFocus: "Take over floor washing and other heavy chores. Her center of gravity is shifting.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  18: {
    week: 18, trimester: 2,
    babyDev: "Baby can yawn, stretch and kick. Bones visible on ultrasound.",
    motherBody: "Abdominal blood vessels dilate — some feel dizzy when standing up quickly.",
    highlight: "Baby stretches and kicks",
    highlightEmoji: "🤸",
    facts: ["Baby stretches and kicks", "Bones visible on scan", "Blood vessels dilate"],
    nutrition: [
      { icon: "🥩", text: "Iron supplement (40–50 mg/day) as recommended by midwife" },
      { icon: "🍊", text: "Vitamin C with every iron-rich meal boosts absorption" },
      { icon: "🌾", text: "Whole grains give B-vitamins and lasting energy" },
    ],
    partnerFocus: "Sign up for the birth prep class now — slots fill up.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  19: {
    week: 19, trimester: 2,
    babyDev: "Baby's senses develop fast. The brain's sensory centers activate.",
    motherBody: "Close to halfway. Noticeable kicks for most now.",
    highlight: "All senses activate",
    highlightEmoji: "✨",
    facts: ["All senses active", "Sensory centers working", "Kicks felt"],
    nutrition: [
      { icon: "🫘", text: "Protein for baby's accelerating growth" },
      { icon: "🥛", text: "Calcium + vitamin D: bone formation at peak" },
      { icon: "🌾", text: "Fibre and regular meals prevent constipation" },
    ],
    partnerFocus: "Make a list of what you still need. Break it down by month.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  20: {
    week: 20, trimester: 2,
    babyDev: "Baby is about 25 cm long (crown to heel). The 20-week anomaly scan shows everything. (Note: measurement switches from crown-rump to crown-heel around now — that's why 'length' suddenly jumps.)",
    motherBody: "HALFWAY! Bump is clear now. Stretch marks may begin — moisturizing helps.",
    highlight: "HALFWAY — 20 weeks!",
    highlightEmoji: "🎉",
    facts: ["Halfway through pregnancy", "20-week anomaly scan", "Baby ~25 cm (crown-heel)"],
    nutrition: [
      { icon: "🐟", text: "DHA omega-3: baby's brain grows fast now" },
      { icon: "🥦", text: "Magnesium from greens helps leg cramps" },
      { icon: "💧", text: "2–2.5 L water — amniotic fluid production high" },
    ],
    partnerFocus: "Celebrate halfway tonight. You've come a long way.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  21: {
    week: 21, trimester: 2,
    babyDev: "Baby sleeps and wakes in its own cycles. Can taste the amniotic fluid.",
    motherBody: "Digestion slows from progesterone. Constipation and heartburn are common now.",
    highlight: "Baby has own sleep cycles",
    highlightEmoji: "💤",
    facts: ["Own sleep cycles", "Baby can taste", "Constipation normal"],
    nutrition: [
      { icon: "🥛", text: "Iodine from dairy/fish: baby's thyroid is forming" },
      { icon: "🥩", text: "Protein and iron for continued rapid growth" },
      { icon: "🫐", text: "Berries and citrus: antioxidants + vitamin C" },
    ],
    partnerFocus: "Start setting up the baby's room together — it bonds you.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  22: {
    week: 22, trimester: 2,
    babyDev: "Baby's lips and eyebrows are fully formed. Hearing sharpens — baby reacts to loud noises.",
    motherBody: "Braxton Hicks (practice contractions) may start now. They are irregular and painless.",
    highlight: "Baby reacts to loud sounds",
    highlightEmoji: "🔊",
    facts: ["Lips and brows fully formed", "Baby reacts to loud sounds", "Practice contractions may start"],
    nutrition: [
      { icon: "🌾", text: "Complex carbs steady blood sugar" },
      { icon: "🐟", text: "DHA from oily fish or algal oil — vision active" },
      { icon: "🥜", text: "Avocado and nuts: healthy fat for brain growth" },
    ],
    partnerFocus: "Practice asking 'what do you need?' instead of jumping to solutions.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  23: {
    week: 23, trimester: 2,
    babyDev: "Baby's skin is still wrinkled — fat layer not yet filled. Lungs maturing.",
    motherBody: "Increased sweating is normal — blood volume up about 40%.",
    highlight: "Blood volume +40%",
    highlightEmoji: "❤️",
    facts: ["Lungs maturing", "Blood volume +40%", "Skin still wrinkled"],
    nutrition: [
      { icon: "🥩", text: "Iron and protein for baby's growth spurt" },
      { icon: "🫘", text: "Chickpeas and lentils: iron, fibre and protein in one" },
      { icon: "🍊", text: "Vitamin C + iron = best duo" },
    ],
    partnerFocus: "Check employer notice rules for starting parental leave.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  24: {
    week: 24, trimester: 2,
    babyDev: "Viability rises gradually from this time forward — it is not a fixed date. Many extremely preterm babies around week 24 can survive with intensive care, but it's individual.",
    motherBody: "Pelvic floor under rising pressure. Pelvic floor exercises matter — 3 sets × 10 daily.",
    highlight: "Viability threshold — gradual",
    highlightEmoji: "🌱",
    facts: ["Viability rises gradually", "Pelvic floor pressured — train daily", "Lungs continue to develop"],
    nutrition: [
      { icon: "🥛", text: "Calcium ~1000 mg/day: baby's lungs and bones harden" },
      { icon: "💊", text: "Vitamin D supports calcium uptake" },
      { icon: "🌾", text: "Fibre prevents constipation and hemorrhoids in trimester 3" },
    ],
    partnerFocus: "Talk about your birth plan: wishes, pain relief, music. It reduces stress on the day.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  25: {
    week: 25, trimester: 2,
    babyDev: "Baby weighs about 700 g. Unique hand and foot lines.",
    motherBody: "Many notice increased kicking after meals. Baby reacts to blood sugar rises.",
    highlight: "Unique handprints form",
    highlightEmoji: "✋",
    facts: ["Unique handprints and footprints", "Baby reacts to blood sugar", "Baby weighs ~700 g"],
    nutrition: [
      { icon: "🥩", text: "Iron and protein daily — body building reserves" },
      { icon: "🐟", text: "Oily fish 2× a week continues" },
      { icon: "🌾", text: "Steady blood sugar = steady baby — avoid quick sugars" },
    ],
    partnerFocus: "Freeze 10–15 meals for leave — the best practical investment.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  26: {
    week: 26, trimester: 2,
    babyDev: "Baby's eyes open for the first time. Baby can distinguish light from dark.",
    motherBody: "Sleep gets hard for many. Lie on your left side — better blood flow.",
    highlight: "Baby opens eyes",
    highlightEmoji: "👀",
    facts: ["Eyes open", "Light and dark distinguished", "Sleep on left side for blood flow"],
    nutrition: [
      { icon: "🥦", text: "Vitamin K from greens prepares blood clotting for birth" },
      { icon: "🐟", text: "DHA continues — vision developing" },
      { icon: "💧", text: "Hydration reduces sleep disruptions" },
    ],
    partnerFocus: "Massage her back and legs daily. It's not a luxury — it relieves real pain.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  27: {
    week: 27, trimester: 2,
    babyDev: "The brain surface starts to fold (gyri). REM sleep active.",
    motherBody: "Trimester 3 is nearly here. Heavy feeling, frequent urination and shortness of breath.",
    highlight: "Baby may already dream",
    highlightEmoji: "🌙",
    facts: ["Brain cortex folds", "REM sleep active", "Trimester 3 around the corner"],
    nutrition: [
      { icon: "🥩", text: "Iron and protein daily — blood volume at peak" },
      { icon: "🐟", text: "Oily fish 2× a week continues" },
      { icon: "🌾", text: "Smaller, more frequent meals as the bump presses" },
    ],
    partnerFocus: "Plan visitor boundaries for the first days home — your call, not the family's.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  28: {
    week: 28, trimester: 3,
    babyDev: "Trimester 3! Baby weighs about 1 kg. Skin smooths as fat fills out.",
    motherBody: "Pelvic loosening is common now. Pain in the symphysis and groin — take it seriously.",
    highlight: "TRIMESTER 3 begins",
    highlightEmoji: "🏁",
    facts: ["Trimester 3 starts", "Baby ~1 kg", "Pelvic pain can occur"],
    nutrition: [
      { icon: "🥦", text: "Vitamin K from greens supports blood clotting at birth" },
      { icon: "🥛", text: "Calcium: bones mineralizing fast" },
      { icon: "🌾", text: "Fibre and water prevent constipation" },
    ],
    partnerFocus: "If glucose screening is offered: drive her there — it's a long visit.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  29: {
    week: 29, trimester: 3,
    babyDev: "Baby can regulate its body temperature. Muscle and bone density rise fast.",
    motherBody: "Breathing can feel heavy — the uterus presses on the diaphragm. That's normal.",
    highlight: "Baby controls temperature",
    highlightEmoji: "🌡️",
    facts: ["Own temperature regulation", "Muscle mass rising", "Heavy breathing for mom"],
    nutrition: [
      { icon: "🐟", text: "DHA omega-3: brain development accelerating" },
      { icon: "🥩", text: "Protein for baby's ~200 g/week growth" },
      { icon: "💊", text: "Talk to midwife about iron levels" },
    ],
    partnerFocus: "Prepare the first weeks home: who visits? When? Set clear boundaries with family.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  30: {
    week: 30, trimester: 3,
    babyDev: "Baby is about 40 cm and weighs 1.3 kg. The brain grows enormously fast.",
    motherBody: "Back pain at its peak. Physiotherapy and water exercise are effective.",
    highlight: "Brain growing explosively",
    highlightEmoji: "🧠",
    facts: ["Brain growth at peak", "Baby ~40 cm and 1.3 kg", "Back pain peaks"],
    nutrition: [
      { icon: "🐟", text: "DHA-rich oily fish continues" },
      { icon: "🥛", text: "Calcium + vitamin D needs highest" },
      { icon: "🌾", text: "Magnesium from whole grains and greens against cramps" },
    ],
    partnerFocus: "Learn signs of preterm labor: regular contractions, downward pressure, water breaking. And the plan if it happens.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  31: {
    week: 31, trimester: 3,
    babyDev: "Baby is turning head down. All organs are fully functional.",
    motherBody: "Sleep is hard. Try a U-pillow, raised head, no screens after 9 pm.",
    highlight: "Baby turns head down",
    highlightEmoji: "🔄",
    facts: ["Baby turns head down", "Organs functional", "Sleep is hard — that's normal"],
    nutrition: [
      { icon: "🐟", text: "Omega-3 continues — lungs and brain in final phase" },
      { icon: "🫘", text: "Plant iron + vitamin C boosts absorption" },
      { icon: "🥛", text: "Calcium demand highest now" },
    ],
    partnerFocus: "Take charge of logistics: who minds siblings/pets? Is the car fueled?",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  32: {
    week: 32, trimester: 3,
    babyDev: "Baby practices breathing intensely. Fingers and toes fully developed with nails.",
    motherBody: "False contractions (Braxton Hicks) intensify. Real ones: regular, stronger, closer.",
    highlight: "Pack the hospital bag",
    highlightEmoji: "🧳",
    facts: ["Breathing practiced intensively", "Fingernails fully formed", "Learn the contraction difference"],
    nutrition: [
      { icon: "🥦", text: "Iron still important — body building reserves" },
      { icon: "🌾", text: "Small, frequent meals against heartburn" },
      { icon: "🐟", text: "Omega-3 from fish or algal oil" },
    ],
    partnerFocus: "Pack the hospital bag — both of yours. It's too late during labor.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  33: {
    week: 33, trimester: 3,
    babyDev: "Baby's bones are fully hardened — except the skull, which stays flexible until birth.",
    motherBody: "Breasts may produce colostrum already — a slightly yellow, sticky liquid.",
    highlight: "Colostrum begins",
    highlightEmoji: "🤱",
    facts: ["Bones fully hardened — except skull", "Colostrum can form", "Baby continues to grow"],
    nutrition: [
      { icon: "🥩", text: "Protein and iron for growth and blood build-up before birth" },
      { icon: "🥛", text: "Calcium + vitamin D for the next 7 weeks" },
      { icon: "🌾", text: "Fibre prevents constipation" },
    ],
    partnerFocus: "Drive the route to the hospital once. Find parking. Know an alternate route.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  34: {
    week: 34, trimester: 3,
    babyDev: "Baby sleeps most of the time. CNS and immune system mature. Eyes focus.",
    motherBody: "Pelvic floor now carries 10+ kg extra. Light incontinence is common — normal.",
    highlight: "Immune system maturing",
    highlightEmoji: "🛡️",
    facts: ["CNS and immune maturing", "Eyes focusing", "Incontinence normal"],
    nutrition: [
      { icon: "🍊", text: "Vitamin C strengthens connective tissue, reduces bleeding risk" },
      { icon: "🐟", text: "Oily fish 2× a week continues" },
      { icon: "💧", text: "Plenty of water — dehydration can trigger contractions" },
    ],
    partnerFocus: "Review the birth plan with the midwife. Know your stance on pain relief.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  35: {
    week: 35, trimester: 3,
    babyDev: "Baby fills almost the whole uterus. Movements feel different.",
    motherBody: "Lightening can begin — the bump 'drops'. Easier breathing, more bladder pressure.",
    highlight: "Bump drops — lightening",
    highlightEmoji: "⬇️",
    facts: ["Space is tight — movements change", "Lightening can begin", "More bladder pressure"],
    nutrition: [
      { icon: "🌾", text: "Small portions as bump presses" },
      { icon: "🥩", text: "Protein keeps energy up" },
      { icon: "💊", text: "Check iron level with doctor/midwife before birth" },
    ],
    partnerFocus: "Be physically available — it can move quickly from now on.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  36: {
    week: 36, trimester: 3,
    babyDev: "Baby is essentially fully developed. Weight continues to rise. Lanugo disappears.",
    motherBody: "Final scans and conversations in many regions — check baby's position with the midwife.",
    highlight: "Essentially fully developed",
    highlightEmoji: "✅",
    facts: ["Essentially fully developed", "Weight rising", "Lanugo disappears"],
    nutrition: [
      { icon: "🌾", text: "Small portions against heartburn and heaviness" },
      { icon: "🥩", text: "Protein keeps energy up" },
      { icon: "💊", text: "Get iron checked — prevent anemia" },
    ],
    partnerFocus: "Check: car seat installed, crib ready, baby clothes washed, diapers and wipes stocked.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  37: {
    week: 37, trimester: 3,
    babyDev: "Baby is full-term. Most babies are ready to be born now, but some still need extra support at birth — especially with breathing. Weight typically 2.8–3.2 kg.",
    motherBody: "The cervix may start to ripen. The mucus plug can come away (brown/pink mucus).",
    highlight: "Full-term — baby is at term",
    highlightEmoji: "🏆",
    facts: ["Full-term", "Mucus plug can come away", "Weight 2.8–3.2 kg"],
    nutrition: [
      { icon: "🌾", text: "Light, small meals — body preparing for birth" },
      { icon: "💧", text: "Hydration — important during labor" },
      { icon: "🥩", text: "Iron and protein daily" },
    ],
    partnerFocus: "Sleep. Get rest. Build energy. Labor demands stamina from both of you.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  38: {
    week: 38, trimester: 3,
    babyDev: "Baby produces surfactant, further maturing the lungs.",
    motherBody: "Labor can start. Follow your midwife's concrete advice on when to contact the birth place.",
    highlight: "Lungs are ready",
    highlightEmoji: "🫁",
    facts: ["Surfactant matures lungs", "Labor can start anytime", "Follow midwife's contraction guidance"],
    nutrition: [
      { icon: "🌾", text: "Steady blood sugar helps if labor starts" },
      { icon: "💧", text: "Hydration — especially important during labor" },
      { icon: "🥩", text: "Iron and protein continue" },
    ],
    partnerFocus: "Sleep with the phone on. Have a plan for what you do if contractions start at night.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  39: {
    week: 39, trimester: 3,
    babyDev: "Baby is typically about 50 cm. Vernix (wax coating) still on the skin.",
    motherBody: "Fatigue and restlessness are normal. Many women feel restless energy the days before birth.",
    highlight: "Birth is near",
    highlightEmoji: "🌅",
    facts: ["About 50 cm", "Vernix protects skin", "Restless energy is normal"],
    nutrition: [
      { icon: "🌾", text: "Light, small meals" },
      { icon: "💧", text: "Hydration" },
      { icon: "🥦", text: "Greens and legumes" },
    ],
    partnerFocus: "Be present. No work, no appointments. Just be there.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
  40: {
    week: 40, trimester: 3,
    babyDev: "Due date. Baby is ready. Typically 3.0–3.5 kg and 50–52 cm long.",
    motherBody: "Due date is an average — about half give birth later. Induction usually offered weeks 41–42.",
    highlight: "DUE DATE — you're ready",
    highlightEmoji: "🎉",
    facts: ["Due date reached", "Many give birth after term", "Induction typically weeks 41–42"],
    nutrition: [
      { icon: "💧", text: "Hydration" },
      { icon: "🌾", text: "Light meals" },
      { icon: "🥩", text: "Maintain iron and protein" },
    ],
    partnerFocus: "Keep the phone charged. Stay calm. She needs your calm more than anything now.",
    activeVitamins: ["d-vitamin", "jern", "omega-3", "calcium"],
  },
};

// ──────────────────────────────────────────────────────────────────────────────
// TRIMESTER CONTENT (symptoms, partner-help, red flags, preparation)
// ──────────────────────────────────────────────────────────────────────────────

export const trimesterContentEN: Record<1 | 2 | 3, TrimesterContent> = {
  1: {
    herSymptoms: [
      "Severe fatigue",
      "Nausea and vomiting",
      "Tender breasts",
      "Mood swings",
      "Frequent urination",
    ],
    partnerHelpTips: [
      "Take over cooking — avoid strong smells",
      "Let her rest without guilt",
      "Ask concretely what she needs",
      "Be patient with mood swings",
      "Go to scans with her — it matters",
    ],
    redFlags: [
      "Heavy bleeding (more than light spotting)",
      "Severe persistent abdominal pain",
      "Fever above 38°C",
      "Persistent violent vomiting where she can't keep fluids down",
    ],
    preparation: [
      "Book midwife",
      "Tell employer when you're ready",
      "Look up rights to paternity / co-parent leave",
    ],
  },
  2: {
    herSymptoms: [
      "Energy returns for many",
      "Clearly bulging belly",
      "Back and ligament pains",
      "Heartburn",
      "Swollen ankles and feet",
      "First kicks felt",
    ],
    partnerHelpTips: [
      "Place a hand on the bump and wait patiently for a kick",
      "Massage her back — it brings major relief",
      "Take charge of groceries and meal plans",
      "Talk to the bump — baby hears your voice now",
      "Put her feet up in the evening",
    ],
    redFlags: [
      "Reduced movement: fewer or weaker kicks than usual from ~week 22",
      "Heavy bleeding",
      "Strong persistent headache, vision changes or sudden swelling (signs of preeclampsia)",
      "Strong regular contractions (threat of preterm labor)",
      "Water breaking before week 37",
      "Fever above 38°C",
    ],
    preparation: [
      "Sign up for birth prep class",
      "Start the conversation about names",
      "Budget and plan for year 1",
      "Buy the most important baby gear",
    ],
  },
  3: {
    herSymptoms: [
      "Fatigue returns",
      "Shortness of breath (uterus pressing)",
      "Pelvic and back pain",
      "Sleep problems",
      "Braxton Hicks (practice contractions)",
      "Light incontinence — common and normal",
    ],
    partnerHelpTips: [
      "Take over everything that needs bending or lifting",
      "Finish packing the hospital bag together",
      "Learn signs of real labor vs. practice contractions",
      "Have the contraction timer ready on your phone",
      "Be physically available — it can move quickly",
    ],
    redFlags: [
      "Markedly reduced fetal movement — contact midwife the same day",
      "Heavy bleeding",
      "Water breaking before week 37",
      "Strong headache, vision changes or sudden swelling",
      "Strong persistent abdominal pain",
      "Fever above 38°C",
      "Strong itching (especially at night on hands and feet)",
    ],
    preparation: [
      "Pack the hospital bag",
      "Install the car seat",
      "Freeze meals for leave",
      "Agree who minds siblings/pets if it moves fast",
      "Drive the route to the hospital",
    ],
  },
};
